#!/bin/bash

if [ $# -eq 1 ]; then
    DIR=$1
else
    echo "Invalid number of args"
    exit 1
fi

mkdir -p log/

for file in $(ls "${DIR}");
do
    echo "Working on ${file}"
    ruby inserter.rb "${DIR}${file}" > log/${file}.log
    echo "Finished..."
done
